#!/usr/bin/python
# -*- coding: utf-8 -*-

"""

 tunneldigger-broker

"""

try:
   from tunneldigger_broker.main import main
   main()
except ImportError as e:
   print('Error: Could not import broker')
   print('Cause: %s' % e)
